### ISSUE TITLE
Can I run the cloudsql-proxy as a standalone service?

### ISSUE THREAD

**Issue by pkyeck** [GoogleCloudPlatform/container-engine-samples#8]
Hi,
I'm trying to connect my GKE to my Cloud SQL instance.
The docs speak about a sidecar-container using the `b.gcr.io/cloudsql-docker/gce-proxy:1.05` image to proxy the requests from `127.0.0.1` through to my Cloud SQL instance - this works like a charm.

But, I'm asking myself if it would be more efficient, if I had one pod behind a service doing the proxying for all other pods instead of having one sidecar container for every pod that wants to access the database?

Tried setting that up, but the IP of the sqlproxy-service isn't allowed to access the Cloud SQL instance:

```
connect ECONNREFUSED <ip of proxy service>:3306
```

Is there a way around this or should I just stick to the one sidecar-container in every pod approach?

Thanks.

**Comment by jeffmendoza** [comment]
Hi, the parameters in this example are for listening on localhost only. As you know containers in a pod share an IP and localhost. The Proxy defaults to this for security reasons, as you're giving it direct access to your database, bypassing any firewalls. To open it up, you would use
`--instances=my-proj:region:db=tcp:0.0.0.0:3306`
In this case you would be taking on the security burden of keeping access to the proxy locked down.
Also, make sure you don't overload the proxy, as it is now a single point of failure.

In general, you might get better, more details responses to general product questions like this on stackoverflow. [Here is a cloud-sql tag.](http://stackoverflow.com/questions/tagged/google-cloud-sql) Also, [here is some more info on the proxy.](https://cloud.google.com/sql/docs/sql-proxy)

**Comment by ahmetb** [comment]
Closing as the question is answered. @pkyeck please feel free to open more issues if you need to.

**Comment by tombmurphy** [comment]
@jeffmendoza thanks for that info ! That's exactly what I'm doing, I've create a pod with 2 replicas with a service in front for the proxy, so it's no longer a single point of failure.

**Comment by zenyui** [comment]
@bluemalkin @pkyeck did either of you guys get this working? If so, would you mind sharing your deployment and service yaml files?

**Comment by drPytho** [comment]
Here is my version of such a file. Probably a bit from perfect, but it works. If there is a better way or something wrong, please tell me.
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-proxy-deployment
  labels:
    app: sql-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sql-proxy
  template:
    metadata:
      labels:
        app: sql-proxy
    spec:
      containers:
      - name: sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: ["/cloud_sql_proxy",
                  "-instances=PROJECT_ID:REGION:DATABASE=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: sql-proxy-service
spec:
  selector:
    app: sql-proxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

```
